### ISSUE TITLE
[protocol review] Allocators can effectively DOS the vault

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/metamorpho#214]
Allocators have the power to set the supply Queue. In particular they are able to set an empty queue, or a queue with only markets that have reached the cap. In effect this means that all the supply goes to the idle liquidity.

I think this is an intended behavior, to have more granular control of the allocation. If this is the case, it should be documented above the `setSupplyQueue` function

**Comment by Rubilmax** [comment]
Documented in the README now
