### ISSUE TITLE
[protocol review] Check enabled market in `reallocate` withdraw loop

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/metamorpho#219]
The `reallocate` does not check that the withdrawn markets are in the `withdrawQueue`. This means that assets could come from unknown parties (legal problem ?) not whitelisted by the curator, potentially after someone has supplied on behalf of the vault on those markets. It also means that the idle amount could be inflated with amounts that were not supplied on the vault

**Comment by QGarchery** [comment]
Re-opening this because I don't understand why we would want that behavior. This is in the same vein as https://github.com/morpho-org/metamorpho/issues/218: basically it's the last safety measure to ensure that allocators cannot interact with markets that have not been previously approved by the curator. The check should only be about checking that the `withdrawRank` of the market is not 0

**Comment by MerlinEgalite** [comment]
It seems there's [no legal reason](https://morpholabs.slack.com/archives/C02NE4SAE4B/p1697723365712959) to do it and it does not seem to be a requirement either

**Comment by QGarchery** [comment]
To provide a little bit more context on why this was closed as not planned: now that there is a way to "force remove" a market (maybe because it is broken), it becomes convenient to be able to rescue funds without having to wait for the timelock. Additionally, putting the cap above 0 on a market that is scheduled for removal is awkward because it potentially  leaves a window for users to supply on that market before it is actually removed
