### ISSUE TITLE
[protocol review] Possible accidental removal of pending transactions

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/metamorpho#221]
The deletion of pending values happen as soon as the current value is updated, whether or not the pending value has actually been used. This means that some awaited change can be accidentally removed by the owner of the vault.
Consider the following scenario:
1. a vault owner wants to plan high fees in the future, and as a counterparty low fees right now
2. the vault owner `submit` high fees, this will be subject to a timelock as expected
3. the vault owner `submit` lower fees, this is effective immediately
4. the vault owner will not be able to `acceptFee` in the future because the `pendingFee` has been deleted by the `_setFee` subroutine

**Comment by MathisGD** [comment]
I think that we should revert instead, and make the owner manually revoke before setting a new value.

**Comment by Rubilmax** [comment]
What should we do about this? I feel like @MathisGD 's suggestion is interesting

**Comment by MerlinEgalite** [comment]
I think it's cleaner and clearer to overwrite the pending value each a value is set. So I'd be in favor of doing nothing

**Comment by MathisGD** [comment]
Fixed by #353

**Comment by MerlinEgalite** [comment]
> Fixed by #353

let's linked it in the PR instead (did it)
