### ISSUE TITLE
Comment that a market in `supplyQueue` can have `cap = 0 and supply > 0`

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/metamorpho#246]
I agree it complexifies things a lot. But I think we should at least add a comment in this case

_Originally posted by @MerlinEgalite in https://github.com/morpho-labs/metamorpho/pull/239#discussion_r1366670376_

**Comment by Rubilmax** [comment]
Yes it is the case ; I'm not sure it deserves to be specifically highlighted but as you want
Note that the README is updated in #225

**Comment by MerlinEgalite** [comment]
Let's forget about it
