### ISSUE TITLE
transferRewards is a bad name

### ISSUE THREAD

**Issue by MathisGD** [morpho-org/metamorpho#251]
Nothing in Morpho Blue nor Metamorpho enforces the rewards distribution mechanism that is envisioned. Plus nothing ensures that the tokens transferred are actually "rewards", but they could well be donations for example.

I propose transferAdditionnalTokens or transferVaultHoldings

**Comment by gabriellavalecia0-cpu** [comment]
> exactly let's wait for [#254](https://github.com/morpho-org/metamorpho/issues/254) to be implemented
