### ISSUE TITLE
Unpredictable timelock mechanism

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/metamorpho#267]
The issue highlighted in https://github.com/cantinasec/review-morpho-blue-1/pull/68#discussion_r1367673403 seems to be fixed with #259. But actually this is a deeper issue where timelock of pending values are variable which can be unexpected. Consider the following scenario:
1. Let's say the timelock is initially of 1 week, mark the current time as `t`
2. People agree to change the timelock to 1 day, a pending value is submitted at `t`, with the intent that it is effective at `t + 7`
3. 3 days later, at `t + 3`, people agree to increase the fee, with the intent that it is effective at `t + 10`
4. At `t + 7` the timelock is accepted
5. After that (starting at `t + 7` and beyond) the fee can be increased

I think that we should change the `submittedAt` field of pending values to a `validFrom` field that would store `block.timestamp + timelock` and the moment where the pending value is set

**Comment by MerlinEgalite** [comment]
Or we can say that the intent below is not correct since timelock update is ongoing and the users should take it into account

> 3 days later, at t + 3, people agree to increase the fee, with the intent that it is effective at t + 10

**Comment by QGarchery** [comment]
> Or we can say that the intent below is not correct since timelock update is ongoing and the users should take it into account

Ok, but then what should be the intent ? It's not easy to convey it because the pending timelock is not set in stone either. If I'm voting and agreeing on a change I want to know when that change is going to be effective
