### ISSUE TITLE
Update to latest version of Blue

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/metamorpho#315]
Just a reminder to update the `morpho-blue` submodule once we have frozen code. Right now the code is not compatible with the latest version of Blue, for example it is calling `MORPHO.expectedSupplyBalance` but this function is named `expectedSupplyAssets` now

**Comment by Rubilmax** [comment]
It's fixed in #307 but still we need to update `morpho-blue` to `main` afterwards
