### ISSUE TITLE
create encoder for MetaMorpho multicall

### ISSUE THREAD

**Issue by julien-devatom** [morpho-org/metamorpho#321]

**Comment by julien-devatom** [comment]
I'm waiting to have a stable version on main to handle this issue

**Comment by MerlinEgalite** [comment]
Why is this issue in this repo btw?

**Comment by Rubilmax** [comment]
To have it next to contracts just as for bundlers, because it's convenient and very low-level

**Comment by MathisGD** [comment]
@julien-devatom what's the state ?
