### ISSUE TITLE
`revoke*` inconsistency should be explained

### ISSUE THREAD

**Issue by adhusson** [morpho-org/metamorpho#364]
https://github.com/morpho-org/metamorpho/blob/cd0d1644bd3f6ec7d79297bfe1e2979509a8793f/src/MetaMorpho.sol#L454-L455

Unlike other `revoke*` functions, the function `revokePendingMarketRemoval` ensures the pending market removal is revoked whether a removal was pending or not. The inconsistency should be addressed in a comment.

**Comment by Rubilmax** [comment]
Why should it be explained and not actually fixed by checking there's a pending market removal beforehand?

**Comment by adhusson** [comment]
Yes that's a possibility. But then I think you can't have a single bundle that guarantees lowering the cap immediately (unless you modify 
#353 by [moving the `removableAt` check of `submitCap` to the "newCap is bigger" branch](https://github.com/morpho-org/metamorpho/pull/353/files#diff-654c1b2b88c5379e79b25c1c0df42db121f692b705307dc057d5808f86b5ea8dR274-L285)).

**Comment by MathisGD** [comment]
I just saw this issue. But I changed the naming so it's ok now no?
