### ISSUE TITLE
Deposit event is emitted before Supply events on blue

### ISSUE THREAD

**Issue by julien-devatom** [morpho-org/metamorpho#377]
MetaMorpho is emitting the `Deposit` event before depositing on blue, which lead to inconsistency (like you cannot handle which morpho events are associated with the vault deposit easily) and complexity of the vault events management.

The `Withdraw` events order is correct, and reallocating events as well.

I have no easy solution now to fix that without changing the code...

By changing the code, The `_supplyMorpho` call has to be added by overriding the `_mint` function, not the `_deposit` one.

**Comment by Rubilmax** [comment]
I believe it is expected as the `Deposit` event corresponds to the minting of shares on the vault, which is performed prior to supplying to Blue

This behavior is coherent with the rest: emit event every time the corresponding storage slots are changed ; so I'd close this
